* Finish conversion

  - Subclass htmloutputbuffer ing org-ruby, to ouput reveal js friendly html (sections etc)
    Can I embed all the revealjs stuff into single layout that the buffer output can be slotted into? If so , then extend ruby-org with that? Pull request?
  - Flatten org structure: every headline is a slide (document this, both text and visually)
  - Make sure the basics ie. bulletpoints, emphasis, bolding etc works

* Make sure code highlighting works

* Support img-only slides (http link to image)

* Support directly embedding html markup

* Lock org parser version

* Upgrade reveal.js version
  And make it less messy. Can I condense all the reveal js assets into single template file?

* Make theme colors configurable
** Overriding/default theme
** Support introducing metadata about slide-specific overrides
** Support supplying a slide-style.css file with css overrides

* Elisp function
** Shell out to the org2lisp tool, then launch open the generated index file

* Jump to page N
** Jump directly to page n, either directly or by specifying line # in original orgfile
** Have elisp support that
